version: '2'
services:
    heinekenwebapp-app:
        image: heinekenwebapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://heinekenwebapp-postgresql:5432/heinekenwebapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    heinekenwebapp-postgresql:
        extends:
            file: postgresql.yml
            service: heinekenwebapp-postgresql
